# Generated by Django 5.1.6 on 2025-03-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Designation', models.CharField(max_length=150)),
                ('About', models.TextField()),
                ('Qualification', models.CharField(max_length=150)),
                ('Email', models.CharField(max_length=150)),
                ('Phone', models.IntegerField()),
            ],
        ),
    ]
