# Generated by Django 5.1.6 on 2025-03-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='departhment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('HOD', models.CharField(max_length=150)),
                ('About', models.TextField()),
                ('staff', models.CharField(max_length=150)),
            ],
        ),
    ]
